### PR TITLE
Better documentation for base provider functionality

### LINKED ISSUE #6: Separate built-in providers to their own page
The built-in providers (`Address`, `Barcode`, `Color`, etc.) should be documented on a separate page. This will help with readability and better search.

### PR DESCRIPTION
**Pull request by bramceulemans**
In order to make scanning easier for the eyes, it was decided that each function / formatter should have it's own section. A formatters section should contain the function name, a description and examples (in a code block).

Documented providers:
- [x] `Faker\Provider\Base`
- [x] `Faker\Provider\Lorem`
- [x] `Faker\Provider\DateTime`
- [x] `Faker\Provider\Internet`
- [x] `Faker\Provider\UserAgent`
- [x] `Faker\Provider\Payment`
- [x] `Faker\Provider\Color`
- [x] `Faker\Provider\File`
- [x] `Faker\Provider\Image`
- [x] `Faker\Provider\Uuid`
- [x] `Faker\Provider\Barcode`
- [x] `Faker\Provider\Miscellaneous`
- [x] `Faker\Provider\Biased`
- [x] `Faker\Provider\HtmlLorem`

This issue closes #6

### CODE REVIEW

**Review by pimjansen — APPROVED** [review]

**Comment by pimjansen** [comment]
@bramceulemans let me know once done so i can clone this to review

**Comment by bramceulemans** [comment]
Will do, it might take a while. I'm currently on the `Faker\Provider\DateTime`.

**Comment by bramceulemans** [comment]
@pimjansen initial version is done.

**Review by pimjansen — APPROVED** [review]

**Comment by pimjansen** [comment]
Awesome work @bramceulemans !

**Pull request merged**
