### PR TITLE
Hungarian fixes implemented to documentation too.

### PR DESCRIPTION
**Pull request by zsoltjanes**

### CODE REVIEW

**Comment by zsoltjanes** [comment]
Can you tell me what was wrong with my pr?

**Comment by bram-pkg** [comment]
My bad, I didn't realise it already got merged into Faker.

**Review by bram-pkg — APPROVED** [review]

**Comment by bram-pkg** [comment]
Thanks for your contribution!

**Comment by zsoltjanes** [comment]
No problem :)

**Pull request merged**
