### PR TITLE
Fix for the optional flags as int and float

### PR DESCRIPTION
**Pull request by pimjansen**

### CODE REVIEW

**Review by bramceulemans — APPROVED** [review]

**Comment by bramceulemans** [comment]
Seems to be a conflict @pimjansen

**Comment by pimjansen** [comment]
@bramceulemans wth it was a brand new clone haha.

Will update

**Comment by bramceulemans** [comment]
Very impressive that you managed to get a conflict, within one commit, yes! 🤣

**Comment by pimjansen** [comment]
@bramceulemans any idea what happened on that ORM support thing? Since if im correct we agreed to do that right but it seems not to be in main?

**Comment by bramceulemans** [comment]
Do you mean in the docs?

**Comment by pimjansen** [comment]
> Do you mean in the docs? 

Yeah since i have no clue what happened here so im curious if it was already in. Since it shows it as change

**Comment by bramceulemans** [comment]
I separated the ORM docs to a separate file yeah

**Comment by pimjansen** [comment]
Ok well, resolved now haha

**Pull request merged**
